### ISSUE TITLE
How to set P/I/D parameters

### ISSUE THREAD

**Issue by ArtlyStyles** [tekdemo/MiniPID#7]
Hi, I am using this code as my autocar steering PID. Imagine I sit inside the car. My steering target is center of the road 5 meters in front me. I want to steer my car so it points to the target. I use sensor to measure my car current orientation. The different of these two, let's call it D,  is how much I want to steer my car. So when I call getOuput, I should use:

steer = getOutput(D, 0)

Correct?

**Comment by ghost** [comment]
@ArtlyStyles 

While this is quite an unconventional use of a PID loop, yes, that's exactly what you would do. I know because I did something very similar to this for a while in my [SwerveIO](https://github.com/jordanbancino/SwerveIO) API. I can't find the exact commit in which it was removed, but at one point in  [the history of MK2SwerveModule.java](https://github.com/jordanbancino/SwerveIO/commits/master/src/main/java/net/bancino/robotics/swerveio/module/MK2SwerveModule.java), I did exactly what you are doing here, and it does work just fine.
